### ISSUE TITLE
installation failed

### ISSUE THREAD

**Issue by newstartech** [Tmbao/amberelectric-usages#10]
try to install this. it comes with this error. Is it not working current version?
![image](https://github.com/user-attachments/assets/0987df4f-f519-4e22-8fcf-ce3c70661f6b)

**Comment by chicknwinner** [comment]
having the same issue

**Comment by Tmbao** [comment]
I'm not too sure what's happening there, I suspect it's due to the minimum HASS version, hopefully it'll be fixed by https://github.com/Tmbao/amberelectric-usages/pull/12

**Comment by Tmbao** [comment]
Can you try out the pre-release version 1.1.1 and see if it works.

**Comment by chicknwinner** [comment]
it installs ok now but fails when i try to add an API key with

Unknown error occurred

**Comment by newstartech** [comment]
try to install again. Just forgot what URL should put in  "Repository" field
![image](https://github.com/user-attachments/assets/16d47984-3c73-4753-bb89-509dcdf5adc9)

**Comment by chicknwinner** [comment]
1.1.1 worked , sorry i didn't read closely enough.

**Comment by newstartech** [comment]
> 1.1.1 worked , sorry i didn't read closely enough.

can you share the exactly field of Repository, ie, https://api.....

**Comment by newstartech** [comment]
found it. it is https://github.com/Tmbao/amberelectric-usages

**Comment by newstartech** [comment]
installed v1.0.1. try to upgrade to v1.1.1 and requires to update HA to 2024.12.3 or later. will try tomorrow

**Comment by Tmbao** [comment]
I've just relaxed the HA requirement in v1.1.2 (prerelease), so you don't have to update your home assistant if you don't want to

**Comment by Tmbao** [comment]
> [!WARNING]
> There could be some bug in v1.1.2 as mentioned in the other issue https://github.com/Tmbao/amberelectric-usages/issues/11#issuecomment-2543335570
