### ISSUE TITLE
Python 3.13 breaks the integration?

### ISSUE THREAD

**Issue by adamk125** [Tmbao/amberelectric-usages#11]
Hi @Tmbao, @tmbaoc 

Use this integration a lot, I know you dont really support it much any more but would be nice if we're able to look into the issue below?

Looks like the latest move to Python 3.13 breaks the integration from the HAOS 14.0 Home Assistant Core Update of 2024.12.1. Below is some detail in the logs.

Happy to help troubleshoot if youre keen to help?

![image](https://github.com/user-attachments/assets/3e5f99ae-dc95-49ce-a842-4356b541730d)

Logger: aiohttp.server
Source: /usr/local/lib/python3.13/site-packages/aiohttp/web_protocol.py:451
First occurred: 6:37:19 AM (1 occurrences)
Last logged: 6:37:19 AM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_protocol.py", line 480, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_app.py", line 569, in _handle
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 86, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 81, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 222, in post
    return await super().post(request, flow_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 74, in wrapper
    return await method(view, request, data, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 122, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 367, in async_configure
    result = await self._async_configure(flow_id, user_input)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 414, in _async_configure
    result = await self._async_handle_step(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        flow, cur_step["step_id"], user_input
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 517, in _async_handle_step
    result: _FlowResultT = await getattr(flow, method)(user_input)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/amberelectric_usages/config_flow.py", line 55, in async_step_user
    self._sites = await self.hass.async_add_executor_job(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self._fetch_sites, token
        ^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/amberelectric_usages/config_flow.py", line 30, in _fetch_sites
    api = amber_api.AmberApi.create(configuration)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'AmberApi' has no attribute 'create'

**Comment by adamk125** [comment]
I believe the issue is pretty simple to fix.

It looks like there's an incompatibility with the Amber Electric integration in Python 3.13, specifically with how the AmberApi class is being instantiated. The error suggests that the create() method no longer exists or has been changed in the latest version of the amberelectric library.

Just need to update the __init__.py file and change this line:
From:  api_instance = amber_api.AmberApi.create(configuration)
To: api_instance = amber_api.AmberApi(configuration)

**Comment by Tmbao** [comment]
Thank you for your help Adam, I might give it a go when I get home

**Comment by adamk125** [comment]
> Thank you for your help Adam, I might give it a go when I get home

No worries mate, I adjusted the init.py file as above but there seems to be more that needs adjusting in the coordinator.py file to adjust for Python 3.13 compatibility. The primary issue seems to be in how the API method get_usage() is being called?

def _get_usages(self) -> list[Usage]:
        today = dt_util.now().date()
        day_4_weeks_ago = today - timedelta(weeks=4)
        # 🔴 POTENTIAL CHANGE: Might need to modify API call
        return self._api.get_usage(
            self.site_id, start_date=day_4_weeks_ago, end_date=today
        )

The amberelectric library may also have been changed for its import structure or class names in Python 3.13

**Comment by Tmbao** [comment]
Can you give the latest version a go

**Comment by adamk125** [comment]
> Can you give the latest version a go

Hi Mate,

OK so two problems when I upgraded HA Core to the latest. I cant updated the integration via HACS any more 
![image](https://github.com/user-attachments/assets/dc188340-9447-4744-940b-6ea87765b59a)

However, when I manually download the 3 modified files in the latest version and put them in the amberelectric_usages folder I get the following errors. It looks like an error with the actual Amber Electric integration as well:

![image](https://github.com/user-attachments/assets/b0031b6c-89cb-481c-adc7-9e4bc046f37f)

![image](https://github.com/user-attachments/assets/a5cd08ed-9060-4084-971b-89ba2d71c62b)

Logger: homeassistant.setup
Source: setup.py:334
First occurred: 6:35:34 AM (1 occurrences)
Last logged: 6:35:34 AM

Setup failed for custom integration 'amberelectric_usages': Unable to import component: cannot import name 'ApiClient' from 'amberelectric' (/usr/local/lib/python3.13/site-packages/amberelectric/__init__.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1014, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self._get_component, True
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1074, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1022, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/amberelectric_usages/__init__.py", line 3, in <module>
    from amberelectric import Configuration, ApiClient
ImportError: cannot import name 'ApiClient' from 'amberelectric' (/usr/local/lib/python3.13/site-packages/amberelectric/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1034, in async_get_component
    self._component_future.result()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1026, in async_get_component
    comp = self._get_component()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1074, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1022, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/amberelectric_usages/__init__.py", line 3, in <module>
    from amberelectric import Configuration, ApiClient
ImportError: cannot import name 'ApiClient' from 'amberelectric' (/usr/local/lib/python3.13/site-packages/amberelectric/__init__.py)

**Comment by XxInvictus** [comment]
In perspective the amberelectric module being used is extremely out of date, this is on 1.1.1 and current is 2.0.12.
I tried to update it in https://github.com/son1cn/amberelectric-usages/pull/1 but after a couple of days of it working I am not seeing the integrations just fail to load 😢

**Comment by Tmbao** [comment]
Sorry I think I broke `main`, just reverted main to the original state, can you checkout the latest changes in [dev](https://github.com/Tmbao/amberelectric-usages/tree/dev), I can't really test it because my account was closed months ago

**Comment by adamk125** [comment]
> Sorry I think I broke `main`, just reverted main to the original state, can you checkout the latest changes in [dev](https://github.com/Tmbao/amberelectric-usages/tree/dev), I can't really test it because my account was closed months ago

I can generate a API Key if you'd like to do some testing?

**Comment by Tmbao** [comment]
Yeah that would be super helpful Bao Truong On 14 Dec 2024, at 3:04 am, adamk125 ***@***.***> wrote:﻿

Sorry I think I broke main, just reverted main to the original state, can you checkout the latest changes in dev, I can't really test it because my account was closed months ago

I can generate a API Key if you'd like to do some testing?

**Comment by adamk125** [comment]
> Yeah that would be super helpful Bao Truong On 14 Dec 2024, at 3:04 am, adamk125 ***@***.***> wrote:﻿ Sorry I think I broke main, just reverted main to the original state, can you checkout the latest changes in dev, I can't really test it because my account was closed months ago I can generate a API Key if you'd like to do some testing? —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>


@Tmbao here you go, let me know when done so I can deactivate it. Add in psk_ before.

329c701246328756eff6d0ffca1adcde

Also, seems like Amber has gotten better since you left them last year. Been with them for close to a year now and overall pricing is better than the rest if you can plan your usage with automations etc and keep on top of it. Might be worth looking at returning :)

**Comment by Tmbao** [comment]
I think I'm mostly done with it, the newest changes are pushed to `dev`, can you try again now and see if it's consistent with what you see in your Amber app.

Edit: you can download the latest changes tagged with pre-release version 1.1.1 via HACS

**Comment by Tmbao** [comment]
> Been with them for close to a year now and overall pricing is better than the rest if you can plan your usage with automations etc and keep on top of it. Might be worth looking at returning :)

Yeah I'm looking forward to installing solar & batteries in the near future and might get back to Amber if everything goes well :)

**Comment by adamk125** [comment]
Hi @Tmbao,

Thanks for all your hard work! Updated to the latest update on HA and installed the 1.1.2 pre-release. The integration is now working. Only one small thing I noticed - there is a discrepancy in the consumption and costs between whats being pulled into HA vs. whats on the website and app.

Example - Thursday this week, consumption 29.17kwh and cost $8.44 in both the website and the app. 
In HA its showing 28.97kwh and $8.04

This is the same for all days for some reason.

![image](https://github.com/user-attachments/assets/f0ae480d-26fd-4a38-aebc-fca488e6ff92)

![image](https://github.com/user-attachments/assets/1f9ae212-4ce8-4576-a131-1a7deafae77d)

Other than that, new version looks like its working. Deleted and re-created the integration and it loads fine with an API key so new install works too :)

**Comment by Tmbao** [comment]
That seems to be huge, 0.2kwh - $0.4 difference, which is $2 per kwh on average. Do you see that same difference across all the days, or just some other differences. And it'll be great if you can spot the hours that are different on that day.

**Comment by adamk125** [comment]
> That seems to be huge, 0.2kwh - $0.4 difference, which is $2 per kwh on average. Do you see that same difference across all the days, or just some other differences. And it'll be great if you can spot the hours that are different on that day.

Exported the usage for the 12th December (+/- 1 day) to see if I can match a pattern, The Usage difference I think can be explained by the use of the NEM time vs. the Start/End Time, using the same logic the costs dont add up properly though. See attached spreadsheet. 

HA is showing exactly the same as calculation for 'Start Time' - hope that makes sense.

[Amber Usage.xlsx](https://github.com/user-attachments/files/18139033/Amber.Usage.xlsx)

![image](https://github.com/user-attachments/assets/c337866e-1a57-4fae-8375-197ab9741fc4)

**Comment by Tmbao** [comment]
Yeah the logic in this integration uses `start_time` which is UTC based and isn't affected by DST. Home Assistant should interpret the UTC time of the events and translate them to your corresponding timezone, so this is expected, or at least it seems to match my expectation on the data from your spreadsheet. Amber app might do a different calculation though, but not sure  how did it get that 29.17 kwh.

**Comment by Tmbao** [comment]
I'm pretty confident that the original issue here has been fixed, there could be some inconsistency due to DST but looking at your spreadsheet data @adamk125, I think it's kinda expected to me. You can now revoke the API token :), thank you for your help troubleshoot the problem.

**Comment by adamk125** [comment]
> I'm pretty confident that the original issue here has been fixed, there could be some inconsistency due to DST but looking at your spreadsheet data @adamk125, I think it's kinda expected to me. You can now revoke the API token :), thank you for your help troubleshoot the problem.

Many thanks mate! And yes I agree its probably just some timezone differences which isnt a big deal. Thanks for updating the integration, the community thanks you :)
