### ISSUE TITLE
bump manifest for current HA libs

### ISSUE THREAD

**Issue by dcarosone** [Tmbao/amberelectric-usages#8]
Note: I know maintenance is paused as you're not currently using this, but I am. You can choose whether to add this trivial change, or leave the issue here as a note for others to find, until you (hopefully) pick up the module again.

Issue: amberelectic was bumped upstream to 1.1.1; amberelectric-usages fails to build with this because it doesn't match the manifest.  

I patched it in my nix config:

```diff
diff --git a/custom_components/amberelectric_usages/manifest.json b/custom_components/amberelectric_usages/manifest.json
index 10e41d1..bdb684a 100644
--- a/custom_components/amberelectric_usages/manifest.json
+++ b/custom_components/amberelectric_usages/manifest.json
@@ -4,7 +4,7 @@
   "iot_class": "cloud_polling",
   "documentation": "https://github.com/Tmbao/amberelectric-usages/blob/master/README.md",
   "issue_tracker": "https://github.com/Tmbao/amberelectric-usages/issues",
-  "requirements": ["amberelectric==1.1.0"],
+  "requirements": ["amberelectric==1.1.1"],
   "codeowners": ["@tmbao"],
   "loggers": ["amberelectric_usages"],
   "version": "1.0.1",
```

**Comment by Tmbao** [comment]
Hi Daniel, this seems trivial enough, feel free to raise a PR if you want, if not I'm happy to do it later today after work
